
title: F S t r
description: [Finite Strip Computer Application Program: Elastic Buckling Analysis and mode visualizer of thin-walled structures.]
show_downloads: true
github:
  zip_url: https://github.com/joaoadelazzari/FStr/tree/master/versions/vs1.1.2
#  tar_url: another value
theme: jekyll-theme-cayman

