
title: |FStr|
description: Finite Strip Computer Application for a Elastic Buckling Analysis of Thin-Walled Structures
show_downloads: true
github:
  zip_url: https://github.com/joaoadelazzari/FStr/releases/download/v1.2.0/FStr_vs1.2.0_Installer_mcr.rar
  tar_url: https://github.com/joaoadelazzari/FStr/releases
theme: jekyll-theme-minimal

# Tracker
analytics: UA-155850473-4 # Google Analytics
